import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "Y/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const user = useUser();
  console.log(user);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#545454] to-[#000000] text-white">
        {user.isSignedIn ? <SignOutButton /> : <SignInButton />}
      </main>
    </>
  );
};

export default Home;
